version: 2
updates:
- package-ecosystem: github-actions
  assignees:
    - shish
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: composer
  assignees:
    - shish
  directory: /
  schedule:
    interval: monthly
